/* The following code was generated by JFlex 1.6.0 */

package phase2;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.lang.*;
import java.util.ArrayList;

class Phase{
	ArrayList simbol_table = new ArrayList();
    public static void main(String[] args) {
        FileReader filereader = null;
        String input = "testcase.txt";
        try {
            filereader = new FileReader(input);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        System.out.println("Lexeme\t\t\t Token\t\t\t simbol_table");
        Yylex yylex = new Yylex(filereader);
        try {
            yylex.yylex();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.0
 * from the specification file <tt>C:/Users/Shahrabadi/Desktop/phases/phase2/phase2.flex</tt>
 */
class Yylex {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\0\1\16\1\20\1\20\1\16\22\0\1\0\2\0\1\4"+
    "\1\0\1\44\1\0\1\54\1\32\1\33\1\43\1\40\1\51\1\42"+
    "\1\46\1\17\1\3\11\2\1\50\1\47\1\0\1\41\1\0\1\45"+
    "\1\0\32\1\1\24\1\5\1\25\3\0\1\13\1\31\1\21\1\23"+
    "\1\11\1\12\1\52\1\30\1\26\1\1\1\37\1\14\1\1\1\27"+
    "\1\22\1\1\1\53\1\7\1\15\1\6\1\10\1\1\1\36\3\1"+
    "\1\34\1\0\1\35\7\0\1\20\u1fa2\0\1\20\1\20\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\10\1\1\3\3\1\1\4\1\5"+
    "\3\1\1\6\1\7\1\10\1\11\1\1\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\1\1\0\1\2\1\0\1\24\11\0\1\1\1\25"+
    "\2\0\1\26\1\0\1\27\5\0\1\30\1\31\1\32"+
    "\1\33\1\34\5\0\1\35\7\0\1\36\1\0\1\37"+
    "\5\0\1\40\1\41\3\0\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\2\0\1\50\1\51\1\0\1\52\1\0"+
    "\1\53\2\0\1\54\1\55\2\0\1\56\1\0\1\57"+
    "\5\0\1\60\1\61\1\62\1\63\1\64\1\65\1\0"+
    "\1\66";

  private static int [] zzUnpackAction() {
    int [] result = new int[129];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\55\0\132\0\207\0\264\0\341\0\u010e\0\u013b"+
    "\0\u0168\0\u0195\0\u01c2\0\u01ef\0\u021c\0\u0249\0\u0276\0\u02a3"+
    "\0\55\0\55\0\u02d0\0\u02fd\0\u032a\0\55\0\55\0\55"+
    "\0\55\0\u0357\0\u0384\0\55\0\u03b1\0\u03de\0\55\0\55"+
    "\0\u040b\0\55\0\55\0\55\0\u0438\0\u0465\0\u0492\0\u04bf"+
    "\0\55\0\u04ec\0\u0519\0\u0546\0\u0573\0\u05a0\0\u05cd\0\u05fa"+
    "\0\u0627\0\u0654\0\u0681\0\55\0\u06ae\0\u06db\0\55\0\u0708"+
    "\0\55\0\u0735\0\u0762\0\u078f\0\u07bc\0\u07e9\0\55\0\55"+
    "\0\55\0\55\0\55\0\u0816\0\u0843\0\u0870\0\u089d\0\u08ca"+
    "\0\u08f7\0\u0924\0\u0951\0\u097e\0\u09ab\0\u09d8\0\u0a05\0\u0a32"+
    "\0\55\0\u0a5f\0\55\0\u0a8c\0\u0ab9\0\u0ae6\0\u0b13\0\u0b40"+
    "\0\55\0\55\0\u0b6d\0\u0b9a\0\u0bc7\0\55\0\55\0\55"+
    "\0\55\0\55\0\55\0\u08f7\0\u0bf4\0\55\0\55\0\u0c21"+
    "\0\55\0\u0c4e\0\55\0\u0c7b\0\u0ca8\0\55\0\55\0\u0cd5"+
    "\0\u0d02\0\55\0\u0d2f\0\55\0\u0d5c\0\u0d89\0\u0db6\0\u0de3"+
    "\0\u0e10\0\55\0\55\0\55\0\55\0\55\0\55\0\u0e3d"+
    "\0\55";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[129];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\2\2\1\3\1\4\1\5\1\6\1\7\1\10\1\2"+
    "\1\11\1\12\1\13\1\2\1\14\1\2\1\15\1\0"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\2"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\2\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\2\2\1\45\57\0\2\3\42\0\1\46\10\0"+
    "\2\47\42\0\1\46\7\0\1\50\4\0\10\50\3\0"+
    "\3\50\2\0\4\50\4\0\2\50\12\0\2\50\2\0"+
    "\3\51\1\0\11\51\3\0\3\51\2\0\4\51\4\0"+
    "\2\51\12\0\2\51\10\0\1\52\20\0\1\53\35\0"+
    "\1\54\57\0\1\55\12\0\1\56\40\0\1\57\70\0"+
    "\1\60\33\0\1\61\27\0\1\62\35\0\1\63\21\0"+
    "\1\64\26\0\1\65\14\0\1\66\33\0\1\67\56\0"+
    "\1\70\55\0\1\71\14\0\1\72\47\0\1\73\41\0"+
    "\1\74\12\0\1\75\62\0\1\76\64\0\1\77\1\100"+
    "\54\0\1\101\1\102\53\0\1\103\24\0\1\104\2\0"+
    "\1\105\12\0\1\106\22\0\1\107\3\0\3\110\2\0"+
    "\10\110\3\0\3\110\2\0\4\110\4\0\2\110\12\0"+
    "\2\110\3\0\2\111\53\0\2\47\52\0\1\112\4\0"+
    "\10\112\3\0\3\112\2\0\4\112\4\0\2\112\12\0"+
    "\2\112\11\0\1\113\55\0\1\114\51\0\1\115\4\0"+
    "\1\116\5\0\1\117\50\0\1\120\62\0\1\121\45\0"+
    "\1\122\63\0\1\123\44\0\1\124\67\0\1\125\26\0"+
    "\16\63\1\0\1\63\1\0\34\63\15\0\1\126\52\0"+
    "\1\127\53\0\1\130\50\0\1\131\54\0\1\132\57\0"+
    "\1\133\65\0\1\134\60\0\1\135\101\0\1\136\7\0"+
    "\1\137\2\0\1\140\54\0\1\141\51\0\1\142\2\0"+
    "\1\143\117\0\1\51\2\0\1\111\1\144\53\0\2\145"+
    "\62\0\1\146\72\0\1\147\35\0\1\150\60\0\1\151"+
    "\62\0\1\152\43\0\1\153\60\0\1\113\45\0\1\154"+
    "\54\0\1\155\57\0\1\156\52\0\1\157\60\0\1\160"+
    "\54\0\1\161\55\0\1\162\54\0\1\163\42\0\2\164"+
    "\60\0\1\165\54\0\1\166\73\0\1\167\47\0\1\170"+
    "\43\0\1\171\103\0\1\172\26\0\1\173\72\0\1\174"+
    "\50\0\1\175\52\0\1\176\63\0\1\177\40\0\1\200"+
    "\46\0\1\201\46\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3690];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\16\1\2\11\3\1\4\11\2\1\1\11"+
    "\2\1\2\11\1\1\3\11\1\1\1\0\1\1\1\0"+
    "\1\11\11\0\1\1\1\11\2\0\1\11\1\0\1\11"+
    "\5\0\5\11\5\0\1\1\7\0\1\11\1\0\1\11"+
    "\5\0\2\11\3\0\6\11\2\0\2\11\1\0\1\11"+
    "\1\0\1\11\2\0\2\11\2\0\1\11\1\0\1\11"+
    "\5\0\6\11\1\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[129];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 170) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;           
    int totalRead = 0;
    while (totalRead < requested) {
      int numRead = zzReader.read(zzBuffer, zzEndRead + totalRead, requested - totalRead);
      if (numRead == -1) {
        break;
      }
      totalRead += numRead;
    }

    if (totalRead > 0) {
      zzEndRead += totalRead;
      if (totalRead == requested) { /* possibly more input available */
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      return false;
    }

    // totalRead = 0: End of stream
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { 
          }
        case 55: break;
        case 2: 
          { phase2.lexInt = Integer.parseInt(yytext());
              System.out.println(phase2.lexInt);
              return phase2.NUMCONST;
	
          }
        case 56: break;
        case 3: 
          { return phase2.DIV_KW;
          }
        case 57: break;
        case 4: 
          { return phase2.LB_KW;
          }
        case 58: break;
        case 5: 
          { return phase2.RB_KW;
          }
        case 59: break;
        case 6: 
          { return phase2.LP_KW;
          }
        case 60: break;
        case 7: 
          { return phase2.RP_KW;
          }
        case 61: break;
        case 8: 
          { return phase2.LCB_KW;
          }
        case 62: break;
        case 9: 
          { return phase2.RCB_KW;
          }
        case 63: break;
        case 10: 
          { return phase2.ADD_KW;
          }
        case 64: break;
        case 11: 
          { return phase2.ASSIGN;
          }
        case 65: break;
        case 12: 
          { return phase2.SUB_KW;
          }
        case 66: break;
        case 13: 
          { return phase2.MUL_KW;
          }
        case 67: break;
        case 14: 
          { return phase2.MOD_KW;
          }
        case 68: break;
        case 15: 
          { return phase2.QUESTION_KW;
          }
        case 69: break;
        case 16: 
          { return phase2.DOT_KW;
          }
        case 70: break;
        case 17: 
          { return phase2.SEMICOLON_KW;
          }
        case 71: break;
        case 18: 
          { return phase2.COLON_KW;
          }
        case 72: break;
        case 19: 
          { return phase2.COMMA_KW;
          }
        case 73: break;
        case 20: 
          { phase2.lexChar = yytext().charAt(1);
              return phase2.CHARCONST;
	
          }
        case 74: break;
        case 21: 
          { return phase2.DIVEQ_KW;
          }
        case 75: break;
        case 22: 
          { return phase2.OR_KW;
          }
        case 76: break;
        case 23: 
          { return phase2.IF_KW;
          }
        case 77: break;
        case 24: 
          { return phase2.PLUSPLUS_KW;
          }
        case 78: break;
        case 25: 
          { return phase2.ADDEQ_KW;
          }
        case 79: break;
        case 26: 
          { return phase2.SUBEQ_KW;
          }
        case 80: break;
        case 27: 
          { return phase2.MINESMINES_KW;
          }
        case 81: break;
        case 28: 
          { return phase2.MULEQ_KW;
          }
        case 82: break;
        case 29: 
          { phase2.lexReal = Double.parseDouble(yytext());
              return phase2.REALCONST;
	
          }
        case 83: break;
        case 30: 
          { return phase2.END_KW;
          }
        case 84: break;
        case 31: 
          { return phase2.AND_KW;
          }
        case 85: break;
        case 32: 
          { return phase2.INTEGER_KW;
          }
        case 86: break;
        case 33: 
          { return phase2.NOT_KW;
          }
        case 87: break;
        case 34: 
          { return phase2.EQ_KW;
          }
        case 88: break;
        case 35: 
          { return phase2.LT_KW;
          }
        case 89: break;
        case 36: 
          { return phase2.LE_KW;
          }
        case 90: break;
        case 37: 
          { return phase2.NE_KW;
          }
        case 91: break;
        case 38: 
          { return phase2.GT_KW;
          }
        case 92: break;
        case 39: 
          { return phase2.GE_KW;
          }
        case 93: break;
        case 40: 
          { phase2.lexBoolean = Boolean.parseBoolean(yytext());
              return phase2.BOOLCONST;
	
          }
        case 94: break;
        case 41: 
          { return phase2.THEN_KW;
          }
        case 95: break;
        case 42: 
          { return phase2.REAL_KW;
          }
        case 96: break;
        case 43: 
          { return phase2.ELSE_KW;
          }
        case 97: break;
        case 44: 
          { return phase2.CASE_KW;
          }
        case 98: break;
        case 45: 
          { return phase2.CHAR_KW;
          }
        case 99: break;
        case 46: 
          { return phase2.BOOLEAN_KW;
          }
        case 100: break;
        case 47: 
          { phase2.lexId = yytext();
              return phase2.ID;
	
          }
        case 101: break;
        case 48: 
          { return phase2.BREAK_KW;
          }
        case 102: break;
        case 49: 
          { return phase2.WHILE_KW;
          }
        case 103: break;
        case 50: 
          { return phase2.RETURN_KW;
          }
        case 104: break;
        case 51: 
          { return phase2.RECORD_KW;
          }
        case 105: break;
        case 52: 
          { return phase2.STATIC_KW;
          }
        case 106: break;
        case 53: 
          { return phase2.SWITCH_KW;
          }
        case 107: break;
        case 54: 
          { return phase2.DEFAULT_KW;
          }
        case 108: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return 0; }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
